# =============================================================================
# STREAMLIT CLOUD SECRETS CONFIGURATION
# =============================================================================
# This file configures API keys for Streamlit Cloud deployment
# 
# SECURITY NOTICE: 
# - These are PLACEHOLDER values
# - Configure real values in Streamlit Cloud dashboard under "Secrets"
# - Never commit real API keys to version control
# =============================================================================

[api_keys]
# Alpha Vantage API (Free tier: 5 calls/min, 500 calls/day)
ALPHA_VANTAGE_API_KEY = "your_alpha_vantage_key_here"

# Reddit API (Free with registration)
REDDIT_CLIENT_ID = "your_reddit_client_id_here"
REDDIT_CLIENT_SECRET = "your_reddit_client_secret_here"
REDDIT_USER_AGENT = "QuantumPortfolioOptimizer/1.0"

# News API (Free tier: 100 requests/day)
NEWS_API_KEY = "your_news_api_key_here"

# Financial Modeling Prep API (Free tier: 250 calls/day)
FMP_API_KEY = "your_fmp_api_key_here"

# Twitter API v2 (Optional)
TWITTER_BEARER_TOKEN = "your_twitter_bearer_token_here"

# Polygon.io API (Optional)
POLYGON_API_KEY = "your_polygon_api_key_here"

# Gemini API (Optional)
GEMINI_API_KEY = "your_gemini_api_key_here"

# =============================================================================
# DEPLOYMENT INSTRUCTIONS:
# 
# 1. In Streamlit Cloud dashboard, go to your app settings
# 2. Click on "Secrets" tab  
# 3. Copy the API keys from your .env file to the secrets section
# 4. Use this format:
#    ALPHA_VANTAGE_API_KEY = "your_actual_key"
#    NEWS_API_KEY = "your_actual_key"
#    etc.
# 
# 5. Save and redeploy
# =============================================================================
